### ISSUE TITLE
update for DSM 6.2.3-25426 update 3

### ISSUE THREAD

**Issue by CatBegemot7** [Jlozde/Xpenology-6.2.3-EasyFix#2]
Please, update this script for work with new update DSM - 6.2.3 - 25426 update 3.
Now it only works up to 6.2.3 25426-2
Thanks

**Comment by LuxKeiwoker** [comment]
I've manually edited the script to put 6.2.3 - 25426 update 3 on the whitelist. It installed fine without any errors and while transcoding seems to be working now, the subject & facial recognition in Moments still does not show any photo album for people. 

If I click on it, it's empty and shows a message on the top stating that photos will be recognized shortly. Even after a day nothing happens and there is no CPU load. A stop/start of the moments app and a full power cycle didn't help.

**Comment by Jlozde** [comment]
6.2.3-25426-3 support added sorry for delay.
