### ISSUE TITLE
can you add dsm7.0.x

### ISSUE THREAD

**Issue by skill7899** [Jlozde/Xpenology-6.2.3-EasyFix#3]
thank you

**Comment by sstraus** [comment]
+1

**Comment by rayqusa** [comment]
+1
7.1.1

**Comment by Jlozde** [comment]
Hello,

DSM 7.0 changed alot of things so i can not easily update this script. Even libraries have been changed. 

For DSM 7.0 you can check following pages,

https://github.com/apriliars3/synocodectool-patch/
https://www.openos.org/threads/redpill7-0cpu.3647/

Good luck.
